Hi folks, welcome to my Data Science Capstone Project. Cheers and rock on!!

In [1]:
import pandas as pd
import numpy as np
import requests
from urllib.request import urlopen as uReq
from bs4 import BeautifulSoup

In [2]:
#Getting the wikipedia page.

url = "https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"
html_doc=requests.get(url)

In [4]:
#Using Beautiful soup to scrap the webpage and focus on the table.

soup = BeautifulSoup(html_doc.text, 'html.parser')
postaltable = soup.find('table', class_ = 'wikitable sortable').find_all('tbody')
 
for rows in postaltable:
    row=rows.find_all('td')

PostalCode = []
Borough=[]
Neighbourhood = []

count =3

#The table follows a pattern. 
# The 1,4,7,10... etc rows are the Borough values
# The 2,5,8,11  etc rows are the Neighbourhood values
# The 3,6,9,12... etc rows are the PostalCode values

for r in row:
    if(count%3 == 0):
        PostalCode.append(str(r.text.strip()))
    if(count%3 == 1):         
        Borough.append(str(r.text.strip()))
    if(count%3 == 2):         
        Neighbourhood.append(str(r.text.strip()))
    count = count+1
    
data = {'PostalCode':PostalCode, 
        'Borough':Borough,
        'Neighbourhood':Neighbourhood
       } 
  
#Thus we have got the values arranged in a dictionary and then we create DataFrame 
df = pd.DataFrame(data)

print(df.head(10))

  PostalCode           Borough                                Neighbourhood
0        M1A      Not assigned                                 Not assigned
1        M2A      Not assigned                                 Not assigned
2        M3A        North York                                    Parkwoods
3        M4A        North York                             Victoria Village
4        M5A  Downtown Toronto                    Regent Park, Harbourfront
5        M6A        North York             Lawrence Manor, Lawrence Heights
6        M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government
7        M8A      Not assigned                                 Not assigned
8        M9A         Etobicoke      Islington Avenue, Humber Valley Village
9        M1B       Scarborough                               Malvern, Rouge

In [5]:
# We filter the dataframe to remove the 'Not assigned' rows.

df_filtered = df[df['Borough'] != 'Not assigned']
df_filtered = df_filtered.sort_values(by ='PostalCode')
df_filtered

    PostalCode      Borough                                      Neighbourhood
9          M1B  Scarborough                                     Malvern, Rouge
18         M1C  Scarborough             Rouge Hill, Port Union, Highland Creek
27         M1E  Scarborough                  Guildwood, Morningside, West Hill
36         M1G  Scarborough                                             Woburn
45         M1H  Scarborough                                          Cedarbrae
..         ...          ...                                                ...
98         M9N         York                                             Weston
107        M9P    Etobicoke                                          Westmount
116        M9R    Etobicoke  Kingsview Village, St. Phillips, Martin Grove ...
143        M9V    Etobicoke  South Steeles, Silverstone, Humbergate, Jamest...
152        M9W    Etobicoke                Northwest, West Humber - Clairville

[103 rows x 3 columns]

In [ ]:
#The shape of the data frame is:

df_filtered.shape

<h1>PART TWO! --> ADDING CO-ORDINATES DATA </h1>

In [9]:
#Getting co-ordinates from url

url = 'http://cocl.us/Geospatial_data'

df_coordinates = pd.read_csv(url)
print(df_coordinates)

    Postal Code   Latitude  Longitude
0           M1B  43.806686 -79.194353
1           M1C  43.784535 -79.160497
2           M1E  43.763573 -79.188711
3           M1G  43.770992 -79.216917
4           M1H  43.773136 -79.239476
..          ...        ...        ...
98          M9N  43.706876 -79.518188
99          M9P  43.696319 -79.532242
100         M9R  43.688905 -79.554724
101         M9V  43.739416 -79.588437
102         M9W  43.706748 -79.594054

[103 rows x 3 columns]

In [10]:
Latitude = df_coordinates['Latitude'].tolist() 
Longitude = df_coordinates['Longitude'].tolist() 

df_filtered['Latitude'] = Latitude
df_filtered['Longitude'] = Longitude

df_filtered

,PostalCode,Borough,Neighbourhood,Latitude,Longitude
9,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
18,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek",43.784535,-79.160497
27,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
36,M1G,Scarborough,Woburn,43.770992,-79.216917
45,M1H,Scarborough,Cedarbrae,43.773136,-79.239476
...,...,...,...,...,...
98,M9N,York,Weston,43.706876,-79.518188
107,M9P,Etobicoke,Westmount,43.696319,-79.532242
116,M9R,Etobicoke,"Kingsview Village, St. Phillips, Martin Grove ...",43.688905,-79.554724
143,M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest...",43.739416,-79.588437
152,M9W,Etobicoke,"Northwest, West Humber - Clairville",43.706748,-79.594054